export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";
export const CREATE_ORDER_RESET = "CREATE_ORDER_RESET";

export const DETAILS_ORDER_REQUEST = "DETAILS_ORDER_REQUEST";
export const DETAILS_ORDER_SUCCESS = "DETAILS_ORDER_SUCCESS";
export const DETAILS_ORDER_FAIL = "DETAILS_ORDER_FAIL";

export const LIST_PERSONAL_ORDERS_REQUEST = "LIST_PERSONAL_ORDERS_REQUEST";
export const LIST_PERSONAL_ORDERS_SUCCESS = "LIST_PERSONAL_ORDERS_SUCCESS";
export const LIST_PERSONAL_ORDERS_FAIL = "LIST_PERSONAL_ORDERS_FAIL";

export const LIST_ALL_ORDERS_REQUEST = "LIST_ALL_ORDERS_REQUEST";
export const LIST_ALL_ORDERS_SUCCESS = "LIST_ALL_ORDERS_SUCCESS";
export const LIST_ALL_ORDERS_FAIL = "LIST_ALL_ORDERS_FAIL";

export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL";
export const DELETE_ORDER_RESET = "DELETE_ORDER_RESET";

export const DELIVER_ORDER_REQUEST = "DELIVER_ORDER_REQUEST";
export const DELIVER_ORDER_SUCCESS = "DELIVER_ORDER_SUCCESS";
export const DELIVER_ORDER_FAIL = "DELIVER_ORDER_FAIL";
export const DELIVER_ORDER_RESET = "DELIVER_ORDER_RESET";

export const DETAILS_ADMIN_DASHBOARD_REQUEST = "DETAILS_ADMIN_DASHBOARD_REQUEST";
export const DETAILS_ADMIN_DASHBOARD_SUCCESS = "DETAILS_ADMIN_DASHBOARD_SUCCESS";
export const DETAILS_ADMIN_DASHBOARD_FAIL = "DETAILS_ADMIN_DASHBOARD_FAIL";

export const DETAILS_SELLER_DASHBOARD_REQUEST = "DETAILS_SELLER_DASHBOARD_REQUEST";
export const DETAILS_SELLER_DASHBOARD_SUCCESS = "DETAILS_SELLER_DASHBOARD_SUCCESS";
export const DETAILS_SELLER_DASHBOARD_FAIL = "DETAILS_SELLER_DASHBOARD_FAIL";
