export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_RESET = "USER_REGISTER_RESET";

export const USER_LOGOUT = "USER_LOGOUT";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const UPDATE_USER_PROFILE_REQUEST = "UPDATE_USER_PROFILE_REQUEST";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_FAIL = "UPDATE_USER_PROFILE_FAIL";
export const UPDATE_USER_PROFILE_RESET = "UPDATE_USER_PROFILE_RESET";

export const LIST_USER_REQUEST = "LIST_USER_REQUEST";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const LIST_USER_FAIL = "LIST_USER_FAIL";

export const CHANGE_USER_ADMIN_REQUEST = "CHANGE_USER_ADMIN_REQUEST";
export const CHANGE_USER_ADMIN_SUCCESS = "CHANGE_USER_ADMIN_SUCCESS";
export const CHANGE_USER_ADMIN_FAIL = "CHANGE_USER_ADMIN_FAIL";
export const CHANGE_USER_ADMIN_RESET = "CHANGE_USER_ADMIN_RESET";

export const CHANGE_USER_SELLER_REQUEST = "CHANGE_USER_SELLER_REQUEST";
export const CHANGE_USER_SELLER_SUCCESS = "CHANGE_USER_SELLER_SUCCESS";
export const CHANGE_USER_SELLER_FAIL = "CHANGE_USER_SELLER_FAIL";
export const CHANGE_USER_SELLER_RESET = "CHANGE_USER_SELLER_RESET";

export const USER_SELLER_NAME = "USER_SELLER_NAME";
export const USER_SELLER_NAME_RESET = "USER_SELLER_NAME_RESET";
